apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubedotnetcoreapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubedotnetcoreapp
    spec:
      containers:
      - name: kubedotnetcoreapp
        image: freddykcontainerregistry.azurecr.io/kubedotnetcoreapp:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubedotnetcoreapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: kubedotnetcoreapp