FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app

COPY . ./out

# build runtime image
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "kubedotnetcoreapp.dll"]