FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app
RUN echo $(pwd)
COPY . ./out
RUN echo $(pwd)
RUN echo $(ls)

# build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
COPY --from=build-env /app/out .
RUN echo $(ls)
ENTRYPOINT ["dotnet", "dotnetcoreapp/kubedotnetcoreapp/kubedotnetcoreapp.dll"]